on: push
name: Gradle build with sonarqube
jobs:
  gradle-build:
    name: gradle build with sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Sonarqube Scan with Gradle Build
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        uses: trideepnag1911/gradle-build-with-sonarqube@v1.0
